<a href="https://colab.research.google.com/github/emily-mynes/DSRP_Gender_Equity_In_NCAA-Emily-Mynes/blob/main/Gender_Equity_in_NCAA_Sports_Emily_Mynes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.feature_selection import SelectKBest
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error, accuracy_score

In [67]:
url = "https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/ncaa_cleaned.csv"
df = pd.read_csv(url)

In [38]:
df['sector_name'][17336: 17345] = 'Public, 4-year or above'
df['sector_name'][34750: 34759] = 'Public, 4-year or above'
df['sector_name'][52378: 52387] = 'Public, 4-year or above'
df['sector_name'][70150: 70159] = 'Public, 4-year or above'
df['sector_name'][132318: 132327] = 'Public, 4-year or above'
df[df['sector_name'].isnull()]

Empty DataFrame
Columns: [year, institution_name, city_txt, state_cd, classification_code, classification_name, ef_male_count, ef_female_count, ef_total_count, sector_name, partic_men, partic_women, sum_partic_men, sum_partic_women, rev_men, rev_women, total_rev_menwomen, exp_men, exp_women, total_exp_menwomen, sports]
Index: []

[0 rows x 21 columns]

In [39]:
df['state_cd'][17336: 17345] = 'None'
df['state_cd'][34750: 34759] = 'None'
df['state_cd'][52378: 52387] = 'None'
df['state_cd'][70150: 70159] = 'None'
df['state_cd'][132318: 132327] = 'None'

In [60]:
df['city_txt'][17336: 17345] = 'None'
df['city_txt'][34750: 34759] = 'None'
df['city_txt'][52378: 52387] = 'None'
df['city_txt'][70150: 70159] = 'None'
df['city_txt'][132318: 132327] = 'None'

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132327 entries, 0 to 132326
Data columns (total 21 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   year                 132327 non-null  int64
 1   institution_name     132327 non-null  object
 2   city_txt             132327 non-null  object
 3   state_cd             132327 non-null  object
 4   classification_code  132327 non-null  int64
 5   classification_name  132327 non-null  object
 6   ef_male_count        132327 non-null  int64
 7   ef_female_count      132327 non-null  int64
 8   ef_total_count       132327 non-null  int64
 9   sector_name          132327 non-null  object
 10  partic_men           61865 non-null   float64
 11  partic_women         68885 non-null   float64
 12  sum_partic_men       132327 non-null  int64
 13  sum_partic_women     132327 non-null  int64
 14  rev_men              61865 non-null   float64
 15  rev_women            68883 non-null   float64
 16  total_rev_menwomen   87134 non-null   float64
 17  exp_men              61865 non-null   float64
 18  exp_women            68885 non-null   float64
 19  total_exp_menwomen   87136 non-null   float64
 20  sports               132327 non-null  object
dtypes: float64(8), int64(7), object(6)
memory usage: 21.2+ MB

In [87]:
for i in range(len(df)):
  if df['partic_men'][i] == 'NaN' and df['sum_partic_men'] == 0:
    df['partic_men'][i] = 0
df[df['partic_men'].isnull()]

,year,institution_name,city_txt,state_cd,classification_code,classification_name,ef_male_count,ef_female_count,ef_total_count,sector_name,...,partic_women,sum_partic_men,sum_partic_women,rev_men,rev_women,total_rev_menwomen,exp_men,exp_women,total_exp_menwomen,sports
5,2015,Alabama A & M University,Normal,AL,2,NCAA Division I-FCS,1923,2300,4223,"Public, 4-year or above",...,21.0,0,21,NaN,410717.0,410717.0,NaN,432648.0,432648.0,Soccer
6,2015,Alabama A & M University,Normal,AL,2,NCAA Division I-FCS,1923,2300,4223,"Public, 4-year or above",...,25.0,0,25,NaN,298164.0,298164.0,NaN,340259.0,340259.0,Softball
8,2015,Alabama A & M University,Normal,AL,2,NCAA Division I-FCS,1923,2300,4223,"Public, 4-year or above",...,16.0,0,16,NaN,321329.0,321329.0,NaN,357485.0,357485.0,Volleyball
9,2015,Alabama A & M University,Normal,AL,2,NCAA Division I-FCS,1923,2300,4223,"Public, 4-year or above",...,9.0,0,9,NaN,127376.0,127376.0,NaN,115216.0,115216.0,Bowling
12,2015,University of Alabama at Birmingham,Birmingham,AL,1,NCAA Division I-FBS,3397,4862,8259,"Public, 4-year or above",...,68.0,0,68,NaN,922348.0,922348.0,NaN,920905.0,920905.0,All Track Combined
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132313,2019,Purdue University Northwest,Hammond,IN,5,NCAA Division II without football,2653,2798,5451,"Public, 4-year or above",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Sailing
132314,2019,Purdue University Northwest,Hammond,IN,5,NCAA Division II without football,2653,2798,5451,"Public, 4-year or above",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Table Tennis
132315,2019,Purdue University Northwest,Hammond,IN,5,NCAA Division II without football,2653,2798,5451,"Public, 4-year or above",...,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN,Weight Lifting
132323,2019,Simon Fraser University,NaN,NaN,4,NCAA Division II with football,5681,6640,12321,NaN,...,19.0,0,19,NaN,381402.0,381402.0,NaN,381402.0,381402.0,Softball
132325,2019,Simon Fraser University,NaN,NaN,4,NCAA Division II with football,5681,6640,12321,NaN,...,19.0,0,19,NaN,402135.0,402135.0,NaN,402135.0,402135.0,Volleyball

np.float64(nan)